name: Jeff Marlow
favicon: null
layout_spectrum: 0.9616871115285903
typography_spectrum: 0.27257449296303093
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6610914736520499
  lightness: 0.47425037575885653
  saturation: 0.7861276969779283
  rhythmicContrast: 0.8299618188757449
purpose: []
